language: cpp

compiler:
    - g++
    - clang

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-default

script:
    - make test
    - cd test
    - ./LiveCodingTest runall
    - make python
    - cd test
    - ./LiveCodingTest runall
    - make python2
    - cd test
    - ./LiveCodingTest runall
    - make clean
