language: cpp

compiler:
  - g++-4.8
  - clang

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev

script:
  - qmake -qt=qt5 -project
  - qmake -qt=qt5 LiveCoding.pro
  - ${CXX} --version
  - make
  - cd test
  - qmake -qt=qt5 -project
  - qmake -qt=qt5 LiveCodingTest.pro
  - ${CXX} --version
  - make
