language: cpp

compiler:
    - g++
    - clang

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev qtmultimedia5-dev libqt5opengl5-dev

script:
    - qmake -qt=qt5 -project
    - qmake -qt=qt5 LiveCoding.pro
    - make
    - qmake -qt=qt5 CONFIG+=with_python QMAKE_CXXFLAGS+=-DWITH_PYTHON LiveCoding.pro
    - make CPPFLAGS+="-DWITH_PYTHON"
    - cd test
    - qmake -qt=qt5 -project
    - qmake -qt=qt5 LiveCodingTest.pro
    - make
    - qmake -qt=qt5 CONFIG+=with_python QMAKE_CXXFLAGS+=-DWITH_PYTHON LiveCodingTest.pro
    - make CPPFLAGS+="-DWITH_PYTHON"
    - ./LiveCodingTest runall
