language: cpp

compiler:
    - gcc
    - clang

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev

script:
  - qmake -qt=qt5 -project
  - qmake -qt=qt5 LiveCoding.pro
  - make
