.TH "src Directory Reference" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBInstances\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAudioInputProcessor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAudioInputProcessor\&.hpp\fP"
.br
.ti -1c
.RI "file \fBAudioOutputProcessor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAudioOutputProcessor\&.hpp\fP"
.br
.ti -1c
.RI "file \fBAudioTest\&.hpp\fP"
.br
.ti -1c
.RI "file \fBBackend\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBackend\&.hpp\fP"
.br
.ti -1c
.RI "file \fBBootLoader\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBootLoader\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCodeEditor\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCodeEditor\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCodeHighlighter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCodeHighlighter\&.hpp\fP"
.br
.ti -1c
.RI "file \fBEditorWindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEditorWindow\&.hpp\fP"
.br
.ti -1c
.RI "file \fBLiveThread\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPyLiveInterpreter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPyLiveInterpreter\&.hpp\fP"
.br
.ti -1c
.RI "file \fBPySoundGenerator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPySoundGenerator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBRenderer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRenderer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSettingsBackend\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSettingsBackend\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSettingsTab\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSettingsTab\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSettingsWindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSettingsWindow\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSoundGenerator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSoundGenerator\&.hpp\fP"
.br
.in -1c
