.TH "AudioInputProcessor" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioInputProcessor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QIODevice\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBprocessData\fP (QByteArray)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioInputProcessor\fP (QObject *parent=0)"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "const QAudioFormat \fBformat\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual qint64 \fBreadData\fP (char *data, qint64 maxlen)"
.br
.ti -1c
.RI "virtual qint64 \fBwriteData\fP (const char *data, qint64 len)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
