.TH "AudioProcessorInstance" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioProcessorInstance \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QThread\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBwrite\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBstartWriting\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAudioProcessorInstance\fP (QObject *parent=0)"
.br
.ti -1c
.RI "virtual void \fBrun\fP () Q_DECL_OVERRIDE"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
