.TH "AudioOutputProcessorTest" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioOutputProcessorTest \- 
.PP
The \fBAudioOutputProcessorTest\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AudioOutputProcessorTest\&.hpp>\fP
.PP
Inherits QObject\&.
.SH "Detailed Description"
.PP 
The \fBAudioOutputProcessorTest\fP class\&. 

\fBTests\fP the AudiOutputProcessor class; functionality tested includes object creation and writing to the audio output\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
