.TH "BehaviourTab" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BehaviourTab \- 
.PP
The \fBLayoutTab\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SettingsTab\&.hpp>\fP
.PP
Inherits \fBSettingsTab\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBcontentChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBehaviourTab\fP (QHash< QString, QVariant > *Settings, QWidget *parent=0)"
.br
.RI "\fI\fBBehaviourTab::BehaviourTab\fP\&. \fP"
.ti -1c
.RI "\fB~BehaviourTab\fP ()"
.br
.RI "\fI\fBBehaviourTab::~BehaviourTab\fP\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QHash< QString, QVariant > * \fBsettings\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBLayoutTab\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
Veit Heller(s0539501) & Tobias Brosge(s0539713)
.RE
.PP
A subclass of \fBSettingsTab\fP that implements one of the tabs of the \fBSettingsWindow\fP in which all configurations regarding behaviour can be found\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BehaviourTab::BehaviourTab (QHash< QString, QVariant > *Settings, QWidget *parent = \fC0\fP)"

.PP
\fBBehaviourTab::BehaviourTab\fP\&. Construcotr of the \fBBehaviourTab\fP class\&. Calls addLayout()\&. 
.SS "BehaviourTab::~BehaviourTab ()"

.PP
\fBBehaviourTab::~BehaviourTab\fP\&. Destructor of the \fBBehaviourTab\fP class\&. Deletes the GUI elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
