.TH "BootLoader" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BootLoader \- 
.PP
The \fBBootLoader\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BootLoader\&.hpp>\fP
.PP
Inherits QObject\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBacceptConnection\fP ()"
.br
.RI "\fI\fBBootLoader::acceptConnection\fP\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBootLoader\fP (const QString &socketName, \fBBackend\fP *parent=0)"
.br
.RI "\fI\fBBootLoader::BootLoader\fP\&. \fP"
.ti -1c
.RI "\fB~BootLoader\fP ()"
.br
.RI "\fI\fBBootLoader::~BootLoader\fP\&. \fP"
.ti -1c
.RI "void \fBstart\fP ()"
.br
.RI "\fI\fBBootLoader::start\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBBootLoader\fP class\&. 

A basic server that listens to new instances of the program being started and registering them with the main application\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BootLoader::BootLoader (const QString &socketName, \fBBackend\fP *parent = \fC0\fP)\fC [explicit]\fP"

.PP
\fBBootLoader::BootLoader\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsocketName\fP 
.br
\fIparent\fP Constructor of the \fBBootLoader\fP class\&. instantiates the socket and registers with the parent\&. 
.RE
.PP

.SS "BootLoader::~BootLoader ()"

.PP
\fBBootLoader::~BootLoader\fP\&. Destructor of the Bootloader class\&. Cleans up the server\&. 
.SH "Member Function Documentation"
.PP 
.SS "void BootLoader::acceptConnection ()\fC [slot]\fP"

.PP
\fBBootLoader::acceptConnection\fP\&. Accepts a connection from a client, registers it with the backend(so it will run in the main app) and kills the original client\&. 
.PP
References Backend::addInstance(), and Backend::nextID()\&.
.PP
Referenced by start()\&.
.SS "void BootLoader::start ()"

.PP
\fBBootLoader::start\fP\&. starts the BootLoader/socket\&. runs asynchronously\&. 
.PP
References acceptConnection()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
