.TH "EditorWindow" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EditorWindow \- 
.PP
The \fBEditorWindow\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EditorWindow\&.hpp>\fP
.PP
Inherits QMainWindow\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBclosing\fP (\fBEditorWindow\fP *)"
.br
.ti -1c
.RI "void \fBcloseAll\fP (\fBEditorWindow\fP *)"
.br
.ti -1c
.RI "void \fBopenSettings\fP (\fBEditorWindow\fP *)"
.br
.ti -1c
.RI "void \fBopenHelp\fP (\fBEditorWindow\fP *)"
.br
.ti -1c
.RI "void \fBrunCode\fP (\fBEditorWindow\fP *)"
.br
.ti -1c
.RI "void \fBstopCode\fP (\fBEditorWindow\fP *)"
.br
.ti -1c
.RI "void \fBtitleChanged\fP (\fBEditorWindow\fP *)"
.br
.ti -1c
.RI "void \fBchangedSetting\fP (\fBEditorWindow\fP *, const QString &, const QVariant &)"
.br
.ti -1c
.RI "void \fBchangedSettings\fP (\fBEditorWindow\fP *, const QHash< QString, QVariant > &)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditorWindow\fP (const QHash< QString, QVariant > &settings, QWidget *parent=0)"
.br
.RI "\fI\fBEditorWindow::EditorWindow\fP\&. \fP"
.ti -1c
.RI "\fB~EditorWindow\fP ()"
.br
.RI "\fI\fBEditorWindow::~EditorWindow\fP\&. \fP"
.ti -1c
.RI "void \fBshowResults\fP (const QString &)"
.br
.RI "\fI\fBEditorWindow::showResults\fP\&. \fP"
.ti -1c
.RI "void \fBwarningDisplay\fP (const QString &)"
.br
.RI "\fI\fBEditorWindow::warningDisplay\fP\&. \fP"
.ti -1c
.RI "void \fBhighlightErroredLine\fP (int)"
.br
.RI "\fI\fBEditorWindow::highlightErroredLine\fP\&. \fP"
.ti -1c
.RI "void \fBcodeStopped\fP ()"
.br
.RI "\fI\fBEditorWindow::codeStopped\fP\&. \fP"
.ti -1c
.RI "QString \fBgetSourceCode\fP () const "
.br
.RI "\fI\fBEditorWindow::getSourceCode\fP\&. \fP"
.ti -1c
.RI "QString \fBgetTitle\fP () const "
.br
.RI "\fI\fBEditorWindow::getTitle\fP\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBcloseEvent\fP (QCloseEvent *)"
.br
.RI "\fI\fBEditorWindow::closeEvent\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBEditorWindow\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
Veit Heller(s0539501) & Tobias Brosge(s0539713)
.RE
.PP
A subclass of QMainWindow that makes the \fBCodeEditor\fP more interactive by implementing save/load and open/close features\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EditorWindow::EditorWindow (const QHash< QString, QVariant > &settings, QWidget *parent = \fC0\fP)"

.PP
\fBEditorWindow::EditorWindow\fP\&. The constructor of the \fBEditorWindow\fP class\&. Sets up the whole UI around the Editor, including slots and signals\&. Also loads the settings and loads the file that was last displayed when closing the editor\&. Also, it deals with platform-specific displaying quirks\&. 
.SS "EditorWindow::~EditorWindow ()"

.PP
\fBEditorWindow::~EditorWindow\fP\&. Destructor of the \fBEditorWindow\fP class\&. Deletes all the GUI elements\&. 
.SH "Member Function Documentation"
.PP 
.SS "void EditorWindow::closeEvent (QCloseEvent *event)\fC [protected]\fP, \fC [virtual]\fP"

.PP
\fBEditorWindow::closeEvent\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIevent\fP reacts to the close signal; saves the current preferences if wanted and exits(SLOT)\&. 
.RE
.PP

.SS "void EditorWindow::codeStopped ()"

.PP
\fBEditorWindow::codeStopped\fP\&. Sets the icon back to normal\&. 
.PP
Referenced by Instances::WindowInstance::codeStopped()\&.
.SS "QString EditorWindow::getSourceCode () const"

.PP
\fBEditorWindow::getSourceCode\fP\&. 
.PP
\fBReturns:\fP
.RS 4
plain text in editor
.RE
.PP
returns code in editor\&. 
.PP
Referenced by Instances::WindowInstance::sourceCode()\&.
.SS "QString EditorWindow::getTitle () const"

.PP
\fBEditorWindow::getTitle\fP\&. 
.PP
\fBReturns:\fP
.RS 4
current file name as string\&.
.RE
.PP
returns current file name\&. 
.PP
Referenced by Instances::WindowInstance::title()\&.
.SS "void EditorWindow::highlightErroredLine (intlineno)"

.PP
\fBEditorWindow::highlightErroredLine\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlineno\fP Highlights a given line in red\&. Signifies an error in that line\&. 
.RE
.PP

.PP
References CodeEditor::highlightErroredLine()\&.
.PP
Referenced by Instances::WindowInstance::highlightErroredLine()\&.
.SS "void EditorWindow::showResults (const QString &returnedValue)"

.PP
\fBEditorWindow::showResults\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIreturnedValue\fP Is called after the execution of the interpreter thread has finished\&. Shows its return code or an exception traceback\&. 
.RE
.PP

.PP
Referenced by Instances::WindowInstance::reportWarning()\&.
.SS "void EditorWindow::warningDisplay (const QString &message)"

.PP
\fBEditorWindow::warningDisplay\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fImessage\fP Displays a warning box containing message\&. 
.RE
.PP

.PP
Referenced by Instances::WindowInstance::reportError()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
