.TH "EditorWindowTest" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EditorWindowTest \- 
.PP
The \fBEditorWindowTest\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EditorWindowTest\&.hpp>\fP
.PP
Inherits QObject\&.
.SH "Detailed Description"
.PP 
The \fBEditorWindowTest\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
Veit Heller(s0539501) & Tobias Brosge(s0539501)
.RE
.PP
\fBTests\fP the \fBEditorWindow\fP class; functionality tested includes object creation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
