.TH "Instances::IInstance" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Instances::IInstance \- 
.PP
The \fBIInstance\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IInstance\&.hpp>\fP
.PP
Inherits QObject\&.
.PP
Inherited by \fBInstances::WindowInstance\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBrunCode\fP (\fBIInstance\fP *)"
.br
.ti -1c
.RI "void \fBstopCode\fP (\fBIInstance\fP *)"
.br
.ti -1c
.RI "void \fBclosing\fP (\fBIInstance\fP *)"
.br
.ti -1c
.RI "void \fBcloseAll\fP ()"
.br
.ti -1c
.RI "void \fBopenHelp\fP (\fBIInstance\fP *)"
.br
.ti -1c
.RI "void \fBopenSettings\fP (\fBIInstance\fP *)"
.br
.ti -1c
.RI "void \fBchangeSetting\fP (\fBIInstance\fP *, const QString &key, QVariant value)"
.br
.ti -1c
.RI "void \fBchangeSettings\fP (\fBIInstance\fP *, const QHash< QString, QVariant > &)"
.br
.ti -1c
.RI "void \fBgetSetting\fP (\fBIInstance\fP *, const QString &key, QVariant &value)"
.br
.ti -1c
.RI "void \fBgetSettings\fP (\fBIInstance\fP *, QHash< QString, QVariant > &settings)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIInstance\fP (int id, QObject *parent=0)"
.br
.ti -1c
.RI "virtual bool \fBclose\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBreportError\fP (const QString &)=0"
.br
.ti -1c
.RI "virtual void \fBreportWarning\fP (const QString &)=0"
.br
.ti -1c
.RI "virtual void \fBcodeStopped\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBhighlightErroredLine\fP (int)=0"
.br
.ti -1c
.RI "virtual QString \fBsourceCode\fP () const =0"
.br
.ti -1c
.RI "virtual QString \fBtitle\fP () const =0"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBID\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBIInstance\fP & \fBoperator=\fP (const \fBIInstance\fP &rhs)"
.br
.ti -1c
.RI "\fBIInstance\fP & \fBoperator=\fP (\fBIInstance\fP &&rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBIInstance\fP class\&. 

Abstract baseclass from which all instances are derived that are managed by the backend\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
