.TH "LayoutTabTest" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayoutTabTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayoutTabTest\fP (QObject *parent=0)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
