.TH "LayoutTab" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayoutTab \- 
.PP
The \fBLayoutTab\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SettingsTab\&.hpp>\fP
.PP
Inherits \fBSettingsTab\fP\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBcontentChanged\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayoutTab\fP (QHash< QString, QVariant > *Settings, QWidget *parent=0)"
.br
.RI "\fI\fBLayoutTab::LayoutTab\fP\&. \fP"
.ti -1c
.RI "\fB~LayoutTab\fP ()"
.br
.RI "\fI\fBLayoutTab::~LayoutTab\fP\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "QHash< QString, QVariant > * \fBsettings\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBLayoutTab\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
Veit Heller(s0539501) & Tobias Brosge(s0539713)
.RE
.PP
A subclass of \fBSettingsTab\fP that implements one of the tabs of the \fBSettingsWindow\fP in which all configurations regarding layout can be found\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LayoutTab::LayoutTab (QHash< QString, QVariant > *Settings, QWidget *parent = \fC0\fP)"

.PP
\fBLayoutTab::LayoutTab\fP\&. Constructor of the \fBLayoutTab\fP class\&. Calls the addLayout member function\&. 
.SS "LayoutTab::~LayoutTab ()"

.PP
\fBLayoutTab::~LayoutTab\fP\&. Destructor of the \fBLayoutTab\fP class\&. Deletes the GUI elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
