.TH "LineHighlighting" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LineHighlighting \- 
.PP
The \fBLineHighlighting\fP helper class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CodeEditor\&.hpp>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLineHighlighting\fP (\fBCodeEditor\fP *editor)"
.br
.ti -1c
.RI "virtual QSize \fBsizeHint\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpaintEvent\fP (QPaintEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBLineHighlighting\fP helper class\&. 


.PP
\fBAuthor:\fP
.RS 4
Veit Heller(s0539501) & Tobias Brosge(s0539713)
.RE
.PP
A helping subclass of QWidget for the codeEditor that is responsible for highlighting the current line\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
