.TH "LiveThread" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LiveThread \- 
.PP
The \fBLiveThread\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LiveThread\&.hpp>\fP
.PP
Inherits QThread\&.
.PP
Inherited by \fBGlLiveThread\fP, \fBPyLiveThread\fP, \fBPySoundThread\fP, and \fBQtSoundThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLiveThread\fP (const long identity, QObject *parent=0)"
.br
.ti -1c
.RI "virtual void \fBrun\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBinitialize\fP (const QString &title, const QString &instructions)=0"
.br
.ti -1c
.RI "virtual bool \fBupdateCode\fP (const QString &title, const QString &instructions)=0"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const long \fBID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBLiveThread\fP class\&. 

A subclass of QThread that is optimized for running the interpreters we need\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
