.TH "PySoundThread" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PySoundThread \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLiveThread\fP\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBdoneSignalReceived\fP (QString exception, int lineno)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdoneSignal\fP (\fBPySoundThread\fP *, QString, int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPySoundThread\fP (const long identity, QObject *parent=0)"
.br
.ti -1c
.RI "void \fBrun\fP () Q_DECL_OVERRIDE"
.br
.ti -1c
.RI "void \fBinitialize\fP (const QString &, const QString &)"
.br
.ti -1c
.RI "bool \fBupdateCode\fP (const QString &, const QString &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const long \fBID\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
