.TH "PySoundGenerator" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PySoundGenerator \- 
.PP
The \fBPySoundGenerator\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PySoundGenerator\&.hpp>\fP
.PP
Inherits QObject\&.
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBdoneSignal\fP (QString, int)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPySoundGenerator\fP (char *, char *)"
.br
.RI "\fI\fBPySoundGenerator::PySoundGenerator\fP\&. \fP"
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "\fI\fBPySoundGenerator::run\fP\&. \fP"
.ti -1c
.RI "bool \fBupdateCode\fP (QString, QString)"
.br
.RI "\fI\fBPySoundGenerator::updateCode\fP\&. \fP"
.ti -1c
.RI "\fB~PySoundGenerator\fP ()"
.br
.RI "\fI\fBPySoundGenerator::~PySoundGenerator\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBPySoundGenerator\fP class\&. 


.PP
\fBAuthor:\fP
.RS 4
Veit Heller(s0539501) & Tobias Brosge(s0539713)
.RE
.PP
A subclass of QThread that implements an environment for sound live coding while keeping the main codeeditor thread clean by dispatching\&. Python-based\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PySoundGenerator::PySoundGenerator (char *progName, char *pyInstructions)"

.PP
\fBPySoundGenerator::PySoundGenerator\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIprogName\fP 
.br
\fIpyInstructions\fP The constructor of the PySoundGeneratorclass\&. Sets up the python interpreter, the instructions with which it will be fed, the class variables and the break shortcut\&. 
.RE
.PP

.SS "PySoundGenerator::~PySoundGenerator ()"

.PP
\fBPySoundGenerator::~PySoundGenerator\fP\&. The destructor of the \fBPySoundGenerator\fP class\&. Kills the python interpreter\&. 
.SH "Member Function Documentation"
.PP 
.SS "void PySoundGenerator::run ()"

.PP
\fBPySoundGenerator::run\fP\&. The main loop\&. Calls the user code executing method and Q_EMITs a signal when it's done\&. 
.SS "bool PySoundGenerator::updateCode (QStringfilename, QStringinstructions)"

.PP
\fBPySoundGenerator::updateCode\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP 
.br
\fIinstructions\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the name of the program could be changed, false otherwise
.RE
.PP
Updates the code of the currently running Python interpreter\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
