.TH "Tests" 3 "Sun Nov 23 2014" "Version 0.4.0" "VetoLC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tests \- 
.PP
The \fBTests\fP struct\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString * \fBname\fP"
.br
.ti -1c
.RI "QObject *(* \fBtestclass\fP )()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBTests\fP struct\&. 

Implements a name/factory function pair\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VetoLC from the source code\&.
