VetoLC: CodeHighlighter Class Reference
CodeHighlighter Class Reference
The CodeHighlighter class.
#include <CodeHighlighter.hpp>
Public Member Functions
CodeHighlighter (QTextDocument *parent=0, int file=0)
CodeHighlighter::CodeHighlighter.
bool setupHighlighting (int file)
CodeHighlighter::setupHighlighting.
int getHighlighting ()
Protected Member Functions
void highlightBlock (const QString &text)
CodeHighlighter::highlightBlock.
Detailed Description
The CodeHighlighter class.
Author
Veit Heller(s0539501) & Tobias Brosge(s0539713)
A subclass of QSyntaxHighlighter that implements Syntax Highlighting(duh!) for the Code Editor class.
Constructor & Destructor Documentation
CodeHighlighter::CodeHighlighter (QTextDocument * parent = 0, int file = 0)
CodeHighlighter::CodeHighlighter.
Parameters
parent
file The constructor of the syntax highlighter. Needs a highlighting file.
References setupHighlighting().
Member Function Documentation
void CodeHighlighter::highlightBlock (const QString & text) protected
CodeHighlighter::highlightBlock.
Parameters
text Highlights blocks(duh) by evaluating the regexes created in the constructor. TODO: Code and time complexity are suboptimal. Is there a better way?
bool CodeHighlighter::setupHighlighting (int file)
CodeHighlighter::setupHighlighting.
Parameters
file Sets up the highlighting rules. TODO: Make it more flexible - File format? TODO: Highlight bracket-pairs TODO: Build quot-pairs ("bla " bla " bla " -> all is highlighted) TODO: don't let the multi line comment trust preview format (see function highlightBlock(...))
Referenced by CodeHighlighter(), and CodeEditor::setHighlighting().
The documentation for this class was generated from the following files:
src/CodeHighlighter.hpp
src/CodeHighlighter.cpp