VetoLC: Renderer Class Reference
Renderer Class Reference
The Renderer class.
#include <Renderer.hpp>
Public Slots
void renderNow ()
Renderer::renderNow.
void renderLater ()
Renderer::renderLater.
bool updateCode (const QString &, const QString &)
Renderer::updateCode.
void updateAudioData (QByteArray)
Renderer::updateAudioData.
void onMessageLogged (QOpenGLDebugMessage message)
Renderer::onMessageLogged.
Signals
void doneSignal (QString)
void errored (QString, int)
Public Member Functions
Renderer (QWindow *parent=0)
Renderer::Renderer.
Renderer (const QString &, const QString &, QWindow *parent=0)
Renderer::Renderer.
~Renderer ()
Renderer::~Renderer.
Protected Member Functions
virtual bool event (QEvent *)
Renderer::event.
virtual void exposeEvent (QExposeEvent *)
Renderer::exposeEvent.
Detailed Description
The Renderer class.
A subclass of QWindow and QOPenGLFunctions that implements a GLSL fragment shader renderer.
Constructor & Destructor Documentation
Renderer::Renderer (QWindow * parent = 0) explicit
Renderer::Renderer.
Parameters
parent Parent object of the render window
Create a new Renderer with default shader
Renderer::Renderer (const QString & filename, const QString & instructions, QWindow * parent = 0) explicit
Renderer::Renderer.
Parameters
filename Name that should shown in the title
instructions Shader code for execution
parent Parent object of the render window
Create a new Renderer with given code and set filename as title
References onMessageLogged(), and updateAudioData().
Renderer::~Renderer ()
Renderer::~Renderer.
Free resources
Member Function Documentation
bool Renderer::event (QEvent * event) protected virtual
Renderer::event.
Parameters
event The event that should be proccessed
Returns
True if the event was successful proccessed, otherwise false
Called if a new event is poped from the event-queue to render on update event and Q_EMIT doneSignal on close event.
References renderNow().
void Renderer::exposeEvent (QExposeEvent *) protected virtual
Renderer::exposeEvent.
Called if the window is ready to start rendering
References renderNow().
void Renderer::onMessageLogged (QOpenGLDebugMessage message) slot
Renderer::onMessageLogged.
Parameters
message Message text
Write the message text in the debug output
Referenced by Renderer().
void Renderer::renderLater () slot
Renderer::renderLater.
Enqueue an update event to event queue
Referenced by renderNow().
void Renderer::renderNow () slot
Renderer::renderNow.
Use the compiled shader to render on the widget
References renderLater().
Referenced by event(), and exposeEvent().
void Renderer::updateAudioData (QByteArray data) slot
Renderer::updateAudioData.
Parameters
data New audio data
Copy the new sound-data to the graphics memory for visualisation
Referenced by Renderer().
bool Renderer::updateCode (const QString & filename, const QString & code) slot
Renderer::updateCode.
Parameters
filename Text for the title
code New shader program code
Returns
True on success, otherwise false.
Set new title and compile new code for the shader program
The documentation for this class was generated from the following files:
src/Renderer.hpp
src/Renderer.cpp