VetoLC: Backend Class Reference
Backend Class Reference
The Backend class.
#include <Backend.hpp>
Public Slots
void settingsWindowRequested (IInstance *)
Backend::settingsWindowRequested.
void openHelp (IInstance *)
Backend::openHelp.
void instanceClosing (IInstance *)
Backend::instanceClosing.
void instanceDestroyed (QObject *)
Backend::instanceDestroyed.
void instanceRunCode (IInstance *)
Backend::instanceRunCode.
void instanceStopCode (IInstance *)
Backend::instanceStopCode.
void instanceChangedSetting (IInstance *, const QString &key, const QVariant &value)
Backend::instanceChangedSetting.
void instanceRequestSetting (IInstance *, const QString &key, QVariant &value)
Backend::instanceRequestSetting.
void instanceChangedSettings (IInstance *, const QHash< QString, QVariant > &)
Backend::instanceChangedSettings.
void instanceRequestSettings (IInstance *, QHash< QString, QVariant > &)
Backend::instanceRequestSettings.
void childSaidCloseAll ()
Backend::childSaidCloseAll.
void getExecutionResults (QtSoundThread *, QString)
Backend::getExecutionResults.
void getExecutionResults (PySoundThread *, QString, int)
void getExecutionResults (PyLiveThread *, QString, int)
void getExecutionResults (GlLiveThread *, QString)
void getError (GlLiveThread *, QString, int)
Signals
void warningSignal (QWidget *, QString)
void closeAction ()
void saveAction ()
void showResults (const QString &)
void childDoSaveSettings ()
Public Member Functions
Backend (QObject *parent=0)
Backend::Backend.
~Backend ()
Backend::~Backend.
void addInstance (IInstance *, bool=true)
Backend::addChild.
void createChild ()
void childExited (IInstance *, QString)
Backend::childExited.
bool isLast ()
Backend::isLast.
bool removeInstance (IInstance *, bool=true)
Backend::removeChild.
bool removeInstance (int, bool=true)
void removeSettings (IInstance *)
Backend::removeSettings.
void removeSettings (int)
void saveAllSettings ()
void saveSettings (IInstance *, QString)
QHash< QString, QVariant > getSettings (IInstance *)
Backend::getSettings.
QHash< QString, QVariant > getSettings (int id)
Backend::getSettings.
int nextID ()
Backend::nextID.
QList< int > loadIds ()
Backend::loadIds.
QVariant getSetting (QString key, QVariant defaultValue=QVariant())
Static Public Member Functions
static QDir directoryOf (const QString &)
Backend::directoryOf.
Detailed Description
The Backend class.
The heart and soul of the eidtors functionality. Is connected to all the other parts of the application (through SIGNALs as well as references) and keeps track of all the windows and code evaluation threads that are created and deleted.
Constructor & Destructor Documentation
Backend::Backend (QObject * parent = 0) explicit
Backend::Backend.
Parameters
parent The constructor of the Backend class. Initializes the editor window list and the thread list as well as the settings backend.
References SettingsBackend::getSettingsFor().
Backend::~Backend ()
Backend::~Backend.
The destructor of the Backend class. Eliminates all the threads that were orphaned when all the windows closed.
Member Function Documentation
void Backend::addInstance (IInstance * instance, bool removeSettings = true)
Backend::addChild.
Parameters
instance
removeSettings Is called by one of the editor window instances; enlists the child and creates an empty thread entry in the list so that the two correlate.
References childSaidCloseAll(), getSettings(), instanceChangedSetting(), instanceChangedSettings(), instanceClosing(), instanceDestroyed(), instanceRequestSetting(), instanceRequestSettings(), instanceRunCode(), instanceStopCode(), openHelp(), SettingsBackend::removeSettings(), and settingsWindowRequested().
Referenced by BootLoader::acceptConnection().
void Backend::childExited (IInstance * child, QString file)
Backend::childExited.
Parameters
child
file Is called by one of the editor window instances; when the child reacts to the closedAction, it is removed from the list.
void Backend::childSaidCloseAll () slot
Backend::childSaidCloseAll.
Is called by one of the editor window instances; when a user requests to exit the application, this will tell all the children to terminate.
References instanceDestroyed(), removeInstance(), and SettingsBackend::removeSettings().
Referenced by addInstance().
QDir Backend::directoryOf (const QString & subdir) static
Backend::directoryOf.
Parameters
subdir
Returns
the directory one wants to navigate into
Platform independent wrapper to changing the directory.
Referenced by openHelp().
void Backend::getExecutionResults (QtSoundThread * thread, QString returnedException) slot
Backend::getExecutionResults.
reacts to the done SIGNAL by terminating the thread and Q_EMITting a showResults SIGNAL for the QWidgets to display
QHash< QString, QVariant > Backend::getSettings (IInstance * instance)
Backend::getSettings.
Parameters
instance
Returns
a list of current settings
Gets all settings for a specific window.
Referenced by addInstance().
QHash< QString, QVariant > Backend::getSettings (int id)
Backend::getSettings.
Parameters
id
Returns
a QHash of all the settings for an id.
looks up the settings for an editor window child.
References SettingsBackend::getSettings().
void Backend::instanceChangedSetting (IInstance * instance, const QString & key, const QVariant & value) slot
Backend::instanceChangedSetting.
Parameters
instance
key
value Reacts to the instance changing settings. Saves the new settings.
References SettingsBackend::saveSettingsFor().
Referenced by addInstance().
void Backend::instanceChangedSettings (IInstance * instance, const QHash< QString, QVariant > & set) slot
Backend::instanceChangedSettings.
Parameters
instance
set Reacts to the instance changing its settings(as a set). Saves the new settings. TODO: Needed(overloaded call)?
References SettingsBackend::saveSettingsFor().
Referenced by addInstance().
void Backend::instanceClosing (IInstance * instance) slot
Backend::instanceClosing.
Parameters
instance Reacts to the closing signal and calls the removeInstance() routine. TODO: Needed?
References removeInstance().
Referenced by addInstance().
void Backend::instanceDestroyed (QObject * instance) slot
Backend::instanceDestroyed.
Parameters
instance Reacts to the destroyed signal and removes the instance from the backends' memory.
References removeInstance().
Referenced by addInstance(), and childSaidCloseAll().
void Backend::instanceRequestSetting (IInstance * instance, const QString & key, QVariant & value) slot
Backend::instanceRequestSetting.
Parameters
instance
key
value Reacts to the instance requesting its settings for a given key.
References SettingsBackend::getSettingsFor().
Referenced by addInstance().
void Backend::instanceRequestSettings (IInstance * instance, QHash< QString, QVariant > & set) slot
Backend::instanceRequestSettings.
Parameters
instance
set TODO: Needed(overloaded call)?
References SettingsBackend::getSettings().
Referenced by addInstance().
void Backend::instanceRunCode (IInstance * instance) slot
Backend::instanceRunCode.
reacts to the run SIGNAL by running the code(duh) that is in the editor at the moment.
References SettingsBackend::getSettingsFor().
Referenced by addInstance().
void Backend::instanceStopCode (IInstance * instance) slot
Backend::instanceStopCode.
Parameters
instance Reacts to the stopCode signal of an instance. Stops the executing context.
Referenced by addInstance().
bool Backend::isLast ()
Backend::isLast.
Returns
true if the child is the last one, false otherwise
checks whether there is only one or no child in the list.
QList< int > Backend::loadIds ()
Backend::loadIds.
Returns
A list of used IDs
Return the list of ids for which settings should exist.
References SettingsBackend::getSettingsFor().
int Backend::nextID ()
Backend::nextID.
Returns
Free to use id
Look up the first free ID for a new Instance.
Referenced by BootLoader::acceptConnection().
void Backend::openHelp (IInstance *) slot
Backend::openHelp.
Opens a help window in HTML.
References directoryOf().
Referenced by addInstance().
bool Backend::removeInstance (Instances::IInstance * instance, bool removeSettings = true)
Backend::removeChild.
Parameters
child Is called by one of the editor window instances; removes the child from the list and closes the thread. Removes all the settings that belong to the current child. BUG: When the settings of the next children are updated, the settings window will display the settings of the killed child. This will result in confusion of the user. TODO: Fix bug!
Referenced by childSaidCloseAll(), instanceClosing(), and instanceDestroyed().
void Backend::removeSettings (IInstance * instance)
Backend::removeSettings.
Parameters
instance removes the settings for a specific file.
References SettingsBackend::removeSettings().
void Backend::settingsWindowRequested (IInstance * instance) slot
Backend::settingsWindowRequested.
Parameters
instance Creates a settings window instance.
Referenced by addInstance().
The documentation for this class was generated from the following files:
src/Backend.hpp
src/Backend.cpp