VetoLC: SettingsBackend Class Reference
SettingsBackend Class Reference
The SettingsBackend class.
#include <SettingsBackend.hpp>
Static Public Member Functions
static QVariant getSettingsFor (QString, const QVariant &)
SettingsBackend::getSettingsFor.
static QVariant getSettingsFor (const QString, const QVariant, const int)
SettingsBackend::getSettingsFor.
static QHash< QString, QVariant > getSettings (const int index)
SettingsBackend::getSettings.
static void addSettings (const QString key, const QVariant value)
SettingsBackend::addSettings.
static void saveSettingsFor (const int id, const QString &key, const QVariant &value)
SettingsBackend::saveSettings.
static void saveSettingsFor (const int id, const QHash< QString, QVariant > &)
static void removeSettings (const int)
SettingsBackend::removeSettings.
Detailed Description
The SettingsBackend class.
A settings backend. Reads from and writes to the platform independent persistent settings.
Member Function Documentation
void SettingsBackend::addSettings (const QString key, const QVariant value) static
SettingsBackend::addSettings.
Parameters
key
value Adds an entry to the global settings.
QHash< QString, QVariant > SettingsBackend::getSettings (const int id) static
SettingsBackend::getSettings.
Parameters
id
Returns
the settings as a QHash
gets the settings for a child window and translates it to a QHash that is returned.
Referenced by Backend::getSettings(), Backend::instanceRequestSettings(), and SettingsWindow::SettingsWindow().
QVariant SettingsBackend::getSettingsFor (QString key, const QVariant & defaultOption) static
SettingsBackend::getSettingsFor.
Parameters
key
defaultOption
Returns
the settings requested
Takes a key and a default option. Gets the settings for the key or returns defaultOption.
Referenced by Backend::Backend(), Backend::instanceRequestSetting(), Backend::instanceRunCode(), and Backend::loadIds().
QVariant SettingsBackend::getSettingsFor (const QString key, const QVariant defaultOption, const int id) static
SettingsBackend::getSettingsFor.
Parameters
key
defaultOption
id
Returns
the settings requested
Takes a key, a default option and the index of the requesting child window. Gets the settings for the key or returns defaultOption.
void SettingsBackend::removeSettings (const int id) static
SettingsBackend::removeSettings.
Parameters
id Removes the settings of a child.
Referenced by Backend::addInstance(), Backend::childSaidCloseAll(), and Backend::removeSettings().
void SettingsBackend::saveSettingsFor (const int id, const QString & key, const QVariant & value) static
SettingsBackend::saveSettings.
Parameters
id
key
value Saves the settings of a instance.
Referenced by Backend::instanceChangedSetting(), and Backend::instanceChangedSettings().
The documentation for this class was generated from the following files:
src/SettingsBackend.hpp
src/SettingsBackend.cpp