VetoLC: Instances::WindowInstance Class Reference
Instances::WindowInstance Class Reference
The Windownstance class.
#include <WindowInstance.hpp>
Public Slots
void gotDestroying (QObject *)
void gotClosing (EditorWindow *)
WindowInstance::gotClosing.
void gotCloseAll (EditorWindow *)
WindowInstance::gotCloseAll.
void gotRunCode (EditorWindow *)
WindowInstance::gotRunCode.
void gotStopCode (EditorWindow *)
WindowInstance::gotStopCode.
void gotOpenHelp (EditorWindow *)
WindowInstance::gotOpenHelp.
void gotOpenSettings (EditorWindow *)
WindowInstance::gotOpenSettings.
void gotChangedSetting (EditorWindow *, const QString &, const QVariant &)
WindowInstance::gotChangedSetting.
void gotChangedSettings (EditorWindow *, const QHash< QString, QVariant > &)
WindowInstance::gotChangedSettings.
Signals
void runCode (IInstance *)
void stopCode (IInstance *)
void closing (IInstance *)
void closeAll ()
void openHelp (IInstance *)
void openSettings (IInstance *)
void changeSetting (IInstance *, const QString &key, QVariant value)
void changeSettings (IInstance *, const QHash< QString, QVariant > &)
void getSetting (IInstance *, const QString &key, QVariant &value)
void getSettings (IInstance *, QHash< QString, QVariant > &settings)
Public Member Functions
WindowInstance (int id, const QHash< QString, QVariant > &settings, QObject *parent=0)
WindowInstance::WindowInstance.
~WindowInstance ()
WindowInstance::~WindowInstance.
virtual QString sourceCode () const
WindowInstance::sourceCode.
virtual QString title () const
WindowInstance::title.
virtual bool close ()
WindowInstance::close.
virtual void reportError (const QString &message)
WindowInstance::reportError.
virtual void reportWarning (const QString &)
WindowInstance::reportWarning.
virtual void highlightErroredLine (int)
WindowInstance::highlightErroredLine.
virtual void codeStopped ()
WindowInstance::codeStopped.
Public Attributes
const int ID
Detailed Description
The Windownstance class.
Delegate from which all windows are derived that are managed by the backend.
Constructor & Destructor Documentation
Instances::WindowInstance::WindowInstance (int id, const QHash< QString, QVariant > & settings, QObject * parent = 0)
WindowInstance::WindowInstance.
Parameters
id
settings
parent Constructor of the delegate.
Instances::WindowInstance::~WindowInstance ()
WindowInstance::~WindowInstance.
Destructor of the delegate.
Member Function Documentation
bool Instances::WindowInstance::close () virtual
WindowInstance::close.
Returns
whether closing has succeeded
Closes the editor window and return a success flag.
Implements Instances::IInstance.
References gotClosing().
void Instances::WindowInstance::codeStopped () virtual
WindowInstance::codeStopped.
Signals that execution of the editor code has finsihed.
Implements Instances::IInstance.
References EditorWindow::codeStopped().
void Instances::WindowInstance::gotChangedSetting (EditorWindow * , const QString & key, const QVariant & value) slot
WindowInstance::gotChangedSetting.
Parameters
key
value Signals that the editors' settings have changed(singla value).
void Instances::WindowInstance::gotChangedSettings (EditorWindow * , const QHash< QString, QVariant > & settings) slot
WindowInstance::gotChangedSettings.
Parameters
settings Signals that the editors' settings have changed(completely).
void Instances::WindowInstance::gotCloseAll (EditorWindow *) slot
WindowInstance::gotCloseAll.
Signals that the editor requested closing of all windows.
void Instances::WindowInstance::gotClosing (EditorWindow *) slot
WindowInstance::gotClosing.
Signals that the editor requested closing.
Referenced by close().
void Instances::WindowInstance::gotOpenHelp (EditorWindow *) slot
WindowInstance::gotOpenHelp.
Signals that the editor requested a help window.
void Instances::WindowInstance::gotOpenSettings (EditorWindow *) slot
WindowInstance::gotOpenSettings.
Signals that the editor requested a settings window.
void Instances::WindowInstance::gotRunCode (EditorWindow *) slot
WindowInstance::gotRunCode.
Signals that the editor requested a run.
void Instances::WindowInstance::gotStopCode (EditorWindow *) slot
WindowInstance::gotStopCode.
Signals that the editor requested stop of execution.
void Instances::WindowInstance::highlightErroredLine (int lineno) virtual
WindowInstance::highlightErroredLine.
Parameters
lineno Highlight line number lineno as errored.
Implements Instances::IInstance.
References EditorWindow::highlightErroredLine().
void Instances::WindowInstance::reportError (const QString & message) virtual
WindowInstance::reportError.
Parameters
message Displays error message in editor.
Implements Instances::IInstance.
References EditorWindow::warningDisplay().
void Instances::WindowInstance::reportWarning (const QString & text) virtual
WindowInstance::reportWarning.
Parameters
text Displays warning message in editor.
Implements Instances::IInstance.
References EditorWindow::showResults().
QString Instances::WindowInstance::sourceCode () const virtual
WindowInstance::sourceCode.
Returns
the editor contents as string
Gets the Editor Content as a QString.
Implements Instances::IInstance.
References EditorWindow::getSourceCode().
QString Instances::WindowInstance::title () const virtual
WindowInstance::title.
Returns
file name as a QString
Gets the file name as a QString.
Implements Instances::IInstance.
References EditorWindow::getTitle().
The documentation for this class was generated from the following files:
src/Instances/WindowInstance.hpp
src/Instances/WindowInstance.cpp