VetoLC: EditorWindow Class Reference
EditorWindow Class Reference
The EditorWindow class.
#include <EditorWindow.hpp>
Signals
void closing (EditorWindow *)
void closeAll (EditorWindow *)
void openSettings (EditorWindow *)
void openHelp (EditorWindow *)
void runCode (EditorWindow *)
void stopCode (EditorWindow *)
void titleChanged (EditorWindow *)
void changedSetting (EditorWindow *, const QString &, const QVariant &)
void changedSettings (EditorWindow *, const QHash< QString, QVariant > &)
Public Member Functions
EditorWindow (const QHash< QString, QVariant > &settings, QWidget *parent=0)
EditorWindow::EditorWindow.
~EditorWindow ()
EditorWindow::~EditorWindow.
void showResults (const QString &)
EditorWindow::showResults.
void warningDisplay (const QString &)
EditorWindow::warningDisplay.
void highlightErroredLine (int)
EditorWindow::highlightErroredLine.
void codeStopped ()
EditorWindow::codeStopped.
QString getSourceCode () const
EditorWindow::getSourceCode.
QString getTitle () const
EditorWindow::getTitle.
Protected Member Functions
virtual void closeEvent (QCloseEvent *)
EditorWindow::closeEvent.
Detailed Description
The EditorWindow class.
Author
Veit Heller(s0539501) & Tobias Brosge(s0539713)
A subclass of QMainWindow that makes the CodeEditor more interactive by implementing save/load and open/close features.
Constructor & Destructor Documentation
EditorWindow::EditorWindow (const QHash< QString, QVariant > & settings, QWidget * parent = 0)
EditorWindow::EditorWindow.
The constructor of the EditorWindow class. Sets up the whole UI around the Editor, including slots and signals. Also loads the settings and loads the file that was last displayed when closing the editor. Also, it deals with platform-specific displaying quirks.
EditorWindow::~EditorWindow ()
EditorWindow::~EditorWindow.
Destructor of the EditorWindow class. Deletes all the GUI elements.
Member Function Documentation
void EditorWindow::closeEvent (QCloseEvent * event) protected virtual
EditorWindow::closeEvent.
Parameters
event reacts to the close signal; saves the current preferences if wanted and exits(SLOT).
void EditorWindow::codeStopped ()
EditorWindow::codeStopped.
Sets the icon back to normal.
Referenced by Instances::WindowInstance::codeStopped().
QString EditorWindow::getSourceCode () const
EditorWindow::getSourceCode.
Returns
plain text in editor
returns code in editor.
Referenced by Instances::WindowInstance::sourceCode().
QString EditorWindow::getTitle () const
EditorWindow::getTitle.
Returns
current file name as string.
returns current file name.
Referenced by Instances::WindowInstance::title().
void EditorWindow::highlightErroredLine (int lineno)
EditorWindow::highlightErroredLine.
Parameters
lineno Highlights a given line in red. Signifies an error in that line.
References CodeEditor::highlightErroredLine().
Referenced by Instances::WindowInstance::highlightErroredLine().
void EditorWindow::showResults (const QString & returnedValue)
EditorWindow::showResults.
Parameters
returnedValue Is called after the execution of the interpreter thread has finished. Shows its return code or an exception traceback.
Referenced by Instances::WindowInstance::reportWarning().
void EditorWindow::warningDisplay (const QString & message)
EditorWindow::warningDisplay.
Parameters
message Displays a warning box containing message.
Referenced by Instances::WindowInstance::reportError().
The documentation for this class was generated from the following files:
src/EditorWindow.hpp
src/EditorWindow.cpp