VetoLC: BootLoader Class Reference
BootLoader Class Reference
The BootLoader class.
#include <BootLoader.hpp>
Public Slots
void acceptConnection ()
BootLoader::acceptConnection.
Public Member Functions
BootLoader (const QString &socketName, Backend *parent=0)
BootLoader::BootLoader.
~BootLoader ()
BootLoader::~BootLoader.
void start ()
BootLoader::start.
Detailed Description
The BootLoader class.
A basic server that listens to new instances of the program being started and registering them with the main application.
Constructor & Destructor Documentation
BootLoader::BootLoader (const QString & socketName, Backend * parent = 0) explicit
BootLoader::BootLoader.
Parameters
socketName
parent Constructor of the BootLoader class. instantiates the socket and registers with the parent.
BootLoader::~BootLoader ()
BootLoader::~BootLoader.
Destructor of the Bootloader class. Cleans up the server.
Member Function Documentation
void BootLoader::acceptConnection () slot
BootLoader::acceptConnection.
Accepts a connection from a client, registers it with the backend(so it will run in the main app) and kills the original client.
References Backend::addInstance(), and Backend::nextID().
Referenced by start().
void BootLoader::start ()
BootLoader::start.
starts the BootLoader/socket. runs asynchronously.
References acceptConnection().
The documentation for this class was generated from the following files:
src/BootLoader.hpp
src/BootLoader.cpp