VetoLC: CodeEditor Class Reference
CodeEditor Class Reference
The CodeEditor class.
#include <CodeEditor.hpp>
Public Member Functions
CodeEditor (QWidget *parent=0, int file=0)
CodeEditor::CodeEditor.
void lineHighlightingPaintEvent (QPaintEvent *event)
CodeEditor::lineHighlightingPaintEvent.
int lineHighlightingWidth ()
CodeEditor::lineHighlightingWidth.
void highlightErroredLine (int)
CodeEditor::highlightErroredLine.
void setHighlighting (int highlighting)
CodeEditor::setHighlighting.
Protected Member Functions
void resizeEvent (QResizeEvent *event)
CodeEditor::resizeEvent.
void keyPressEvent (QKeyEvent *e)
CodeEditor::keyPressEvent.
Detailed Description
The CodeEditor class.
Author
Veit Heller(s0539501) & Tobias Brosge(s0539713)
A subclass of QPlainTextEdit that is optimized for code; with Syntax Highlighting, line numbers and highlighting of the current line.
Constructor & Destructor Documentation
CodeEditor::CodeEditor (QWidget * parent = 0, int file = 0)
CodeEditor::CodeEditor.
Parameters
parent
file The constructor of the code editor. Sets up the highlighting of syntax and current line and connects slots and signals. Needs a highlighting file.
Member Function Documentation
void CodeEditor::highlightErroredLine (int lineno)
CodeEditor::highlightErroredLine.
Parameters
lineno highlights the line given as argument as errored.
Referenced by EditorWindow::highlightErroredLine().
void CodeEditor::keyPressEvent (QKeyEvent * e) protected
CodeEditor::keyPressEvent.
Parameters
e intercepts the keyPressEvent e so that a tab is rendered as 4 spaces.
void CodeEditor::lineHighlightingPaintEvent (QPaintEvent * event)
CodeEditor::lineHighlightingPaintEvent.
Parameters
event updates the line highlighting whenever scrolling happens; invoked from updateLineHighlighting().
int CodeEditor::lineHighlightingWidth ()
CodeEditor::lineHighlightingWidth.
Returns
the width of the line to be highlighted
Helper function that computes the width of the line that is to be highlighted.
Referenced by resizeEvent().
void CodeEditor::resizeEvent (QResizeEvent * e) protected
CodeEditor::resizeEvent.
Parameters
e catches the resize signal and customizes the update(SLOT)
References lineHighlightingWidth().
void CodeEditor::setHighlighting (int highlighting)
CodeEditor::setHighlighting.
Parameters
highlighting Tells the syntax highlighter to change highlighting by using a code where 0 and 3 stand for Python, 1 stands for Qt and 2 stands for GLSL.
References CodeHighlighter::setupHighlighting().
The documentation for this class was generated from the following files:
src/CodeEditor.hpp
src/CodeEditor.cpp